"""
Project management routes for Image Service.
"""
import os
import uuid
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import JSONResponse

from app.safe_path import resolve_safe_path
from app.schemas import ProjectCreateResponse, ProjectInfo, _validate_project_id

router = APIRouter(prefix="/api/projects", tags=["projects"])

PROJECTS_ROOT = "/app/data/projects"

# 测试模式：使用固定 project_id，解决 UI test mock 链路 ID 一致性问题
_TEST_MODE = os.environ.get("IMAGE_SERVICE_TEST_MODE", "").lower() in ("true", "1")
_TEST_PROJECT_ID = "img-proj-001"


def _project_path(project_id: str) -> str:
    """Resolve project directory with path traversal protection."""
    try:
        return resolve_safe_path(PROJECTS_ROOT, project_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


def _generate_project_id() -> str:
    """Generate a project ID. In test mode uses a fixed ID."""
    if _TEST_MODE:
        return _TEST_PROJECT_ID
    return uuid.uuid4().hex


@router.post(
    "",
    response_model=ProjectCreateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create an image project directory (ID auto-generated by service)",
)
async def create_project() -> ProjectCreateResponse:
    """Create an empty project directory. Project ID is generated by the service."""
    project_id = _generate_project_id()
    path = _project_path(project_id)
    print(f"[DEBUG:project] create_project START project_id={project_id} path={path} test_mode={_TEST_MODE}", flush=True)
    print(f"[DEBUG:project] PROJECTS_ROOT={PROJECTS_ROOT} exists={os.path.isdir(PROJECTS_ROOT)}", flush=True)
    if os.path.isdir(path):
        print(f"[DEBUG:project] create_project ALREADY_EXISTS project_id={project_id}", flush=True)
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content={"project_id": project_id, "message": "already exists"},
        )
    try:
        os.makedirs(path, exist_ok=True)
        print(f"[DEBUG:project] create_project CREATED project_id={project_id} path={path} dir_exists={os.path.isdir(path)}", flush=True)
    except Exception as e:
        print(f"[DEBUG:project] create_project ERROR project_id={project_id} error={str(e)}", flush=True)
        raise HTTPException(status_code=500, detail=f"Failed to create project: {str(e)}")
    return ProjectCreateResponse(project_id=project_id)


@router.get(
    "/{project_id}",
    response_model=ProjectInfo,
    summary="Check if an image project exists",
)
async def get_project(project_id: str) -> ProjectInfo:
    """Return whether the project directory exists."""
    validated = _validate_project_id(project_id)
    return ProjectInfo(project_id=validated, exists=os.path.isdir(_project_path(validated)))


@router.delete(
    "/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete an image project directory (idempotent)",
)
async def delete_project(project_id: str) -> None:
    """Recursively delete the project directory. Idempotent."""
    validated = _validate_project_id(project_id)
    path = _project_path(validated)
    if os.path.isdir(path):
        import shutil
        shutil.rmtree(path)
    return None
