FROM mcr.microsoft.com/playwright:v1.59.1-jammy

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY package*.json ./
RUN npm ci

RUN npm install -g allure-commandline

COPY . .
