"""
Project management routes for Build Service.
"""
import os
import uuid
import tarfile
import io
import shutil
from fastapi import APIRouter, HTTPException, status, Request
from fastapi.responses import JSONResponse

from app.safe_path import resolve_safe_path
from app.schemas import (
    ProjectCreateResponse,
    ProjectInfo,
    UploadResponse,
    _validate_project_id,
)
from app.strategies import get_game_type

router = APIRouter(prefix="/api/projects", tags=["projects"])

PROJECTS_ROOT = "/app/data/projects"

# Test mode: use fixed project_id for UI test mock chain consistency
_TEST_MODE = os.environ.get("BUILD_SERVICE_TEST_MODE", "").lower() in ("true", "1")
_TEST_PROJECT_ID = "build-proj-001"


def _project_path(project_id: str) -> str:
    """Resolve project directory with path traversal protection."""
    try:
        return resolve_safe_path(PROJECTS_ROOT, project_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


def _generate_project_id() -> str:
    """Generate a project ID. In test mode uses a fixed ID."""
    if _TEST_MODE:
        return _TEST_PROJECT_ID
    return uuid.uuid4().hex


@router.post(
    "",
    response_model=ProjectCreateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a build project directory (ID auto-generated by service)",
)
async def create_project() -> ProjectCreateResponse:
    """Create an empty project directory. Project ID is generated by the service."""
    project_id = _generate_project_id()
    path = _project_path(project_id)
    print(f"[DEBUG:project] create_project START project_id={project_id} path={path} test_mode={_TEST_MODE}", flush=True)
    print(f"[DEBUG:project] PROJECTS_ROOT={PROJECTS_ROOT} exists={os.path.isdir(PROJECTS_ROOT)}", flush=True)
    if os.path.isdir(path):
        print(f"[DEBUG:project] create_project ALREADY_EXISTS project_id={project_id}", flush=True)
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content={"project_id": project_id, "message": "already exists"},
        )
    try:
        os.makedirs(path, exist_ok=True)
        print(f"[DEBUG:project] create_project CREATED project_id={project_id} path={path} dir_exists={os.path.isdir(path)}", flush=True)
    except Exception as e:
        print(f"[DEBUG:project] create_project ERROR project_id={project_id} error={str(e)}", flush=True)
        raise HTTPException(status_code=500, detail=f"Failed to create project: {str(e)}")
    return ProjectCreateResponse(project_id=project_id)


@router.get(
    "/{project_id}",
    response_model=ProjectInfo,
    summary="Check if a build project exists",
)
async def get_project(project_id: str) -> ProjectInfo:
    """Return whether the project directory exists."""
    validated = _validate_project_id(project_id)
    path = _project_path(validated)
    exists = os.path.isdir(path)
    info = ProjectInfo(project_id=validated, exists=exists)
    if exists:
        try:
            info.game_type = get_game_type(path)
        except Exception:
            pass
        # Count files
        file_count = 0
        for dirpath, _, filenames in os.walk(path):
            file_count += len(filenames)
        info.file_count = file_count
    return info


@router.delete(
    "/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a build project directory (idempotent)",
)
async def delete_project(project_id: str) -> None:
    """Recursively delete the project directory. Idempotent."""
    validated = _validate_project_id(project_id)
    path = _project_path(validated)
    if os.path.isdir(path):
        shutil.rmtree(path)
    return None


@router.post(
    "/{project_id}/upload",
    response_model=UploadResponse,
    summary="Upload game source as tar.gz and extract to project directory",
)
async def upload_source(project_id: str, request: Request) -> UploadResponse:
    """
    Upload game source code as a tar.gz binary stream.

    Validates project_id, receives raw binary body, extracts to project directory.
    Max size: 200MB.
    """
    validated = _validate_project_id(project_id)
    path = _project_path(validated)

    # Ensure project dir exists
    if not os.path.isdir(path):
        raise HTTPException(status_code=404, detail=f"Project not found: {validated}")

    # Read raw body with size limit (200MB)
    max_size = 200 * 1024 * 1024
    body = await request.body()
    if len(body) > max_size:
        raise HTTPException(
            status_code=413,
            detail=f"Upload too large: {len(body)} bytes (max {max_size})",
        )
    if len(body) == 0:
        raise HTTPException(status_code=400, detail="Empty upload body")

    print(f"[DEBUG:project] upload_source START project_id={validated} size={len(body)}", flush=True)

    try:
        tar_bytes = io.BytesIO(body)
        with tarfile.open(fileobj=tar_bytes, mode="r:gz") as tar:
            # Safety: check for path traversal in archive
            for member in tar.getmembers():
                # Prevent absolute paths and path traversal
                if member.name.startswith("/") or ".." in member.name:
                    raise ValueError(f"Unsafe path in archive: {member.name}")
            tar.extractall(path=path, filter="data")
    except tarfile.TarError as e:
        raise HTTPException(status_code=400, detail=f"Invalid tar.gz: {str(e)}")
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    # Clean old node_modules so fresh npm install picks up correct deps
    nm = os.path.join(path, "node_modules")
    if os.path.isdir(nm):
        print(f"[DEBUG:project] Removing old node_modules for clean build", flush=True)
        shutil.rmtree(nm)

    # Count files
    file_count = 0
    for _, _, filenames in os.walk(path):
        file_count += len(filenames)

    print(f"[DEBUG:project] upload_source DONE project_id={validated} file_count={file_count}", flush=True)
    return UploadResponse(
        success=True,
        message=f"Source uploaded and extracted to project {validated}",
        file_count=file_count,
    )
