"""
Project management routes for Drawio Service.
"""

import os
import shutil
import uuid
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import JSONResponse

from app.safe_path import resolve_safe_path

from app.schemas import ProjectCreateResponse, ProjectInfo, _validate_project_id

router = APIRouter(prefix="/api/projects", tags=["projects"])

PROJECTS_ROOT = "/app/data/projects"

# 测试模式：使用固定 project_id，解决 UI test mock 链路 ID 一致性问题
_TEST_MODE = os.environ.get("DRAWIO_SERVICE_TEST_MODE", "").lower() in ("true", "1")
_TEST_PROJECT_ID = "drw-proj-001"


def _project_path(project_id: str) -> str:
    """Resolve project directory with path traversal protection."""
    try:
        return resolve_safe_path(PROJECTS_ROOT, project_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


def _generate_project_id() -> str:
    """Generate a project ID. In test mode uses a fixed ID."""
    if _TEST_MODE:
        return _TEST_PROJECT_ID
    return uuid.uuid4().hex


@router.post(
    "",
    response_model=ProjectCreateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a project directory (ID auto-generated by service)",
)
async def create_project() -> ProjectCreateResponse:
    """Create an empty project directory. Project ID is generated by the service."""
    project_id = _generate_project_id()
    path = _project_path(project_id)
    if os.path.isdir(path):
        # Idempotent: if already exists, return 200 instead of error
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content={"project_id": project_id, "message": "already exists"},
        )
    os.makedirs(path, exist_ok=True)
    return ProjectCreateResponse(project_id=project_id)


@router.get(
    "/{project_id}",
    response_model=ProjectInfo,
    summary="Check if a project exists",
)
async def get_project(project_id: str) -> ProjectInfo:
    """Return whether the project directory exists."""
    validated = _validate_project_id(project_id)
    return ProjectInfo(project_id=validated, exists=os.path.isdir(_project_path(validated)))


@router.delete(
    "/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a project directory (idempotent)",
)
async def delete_project(project_id: str) -> None:
    """
    Recursively delete the project directory.
    Idempotent: returns 204 even if the directory does not exist.
    """
    validated = _validate_project_id(project_id)
    path = _project_path(validated)
    if os.path.isdir(path):
        shutil.rmtree(path)
    # Always return 204
    return None
